// AUTOGENERATED — non modificare a mano.
// Rigenerare con MCP Supabase generate_typescript_types su lbdwvgcnwvkisrjqremx.
// Dopo ogni migration: rigenerare.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_users: {
        Row: {
          added_at: string
          added_by: string | null
          notes: string | null
          user_id: string
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          notes?: string | null
          user_id: string
        }
        Update: {
          added_at?: string
          added_by?: string | null
          notes?: string | null
          user_id?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          available: boolean
          color_from: string | null
          color_to: string | null
          created_at: string
          icon_name: string | null
          id: string
          kanji: string | null
          label: string
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          available?: boolean
          color_from?: string | null
          color_to?: string | null
          created_at?: string
          icon_name?: string | null
          id: string
          kanji?: string | null
          label: string
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          available?: boolean
          color_from?: string | null
          color_to?: string | null
          created_at?: string
          icon_name?: string | null
          id?: string
          kanji?: string | null
          label?: string
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      closures: {
        Row: {
          closes_dinner: boolean
          closes_lunch: boolean
          created_at: string
          end_date: string
          id: string
          reason: string | null
          start_date: string
        }
        Insert: {
          closes_dinner?: boolean
          closes_lunch?: boolean
          created_at?: string
          end_date: string
          id?: string
          reason?: string | null
          start_date: string
        }
        Update: {
          closes_dinner?: boolean
          closes_lunch?: boolean
          created_at?: string
          end_date?: string
          id?: string
          reason?: string | null
          start_date?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          address_default: Json | null
          created_at: string
          email: string
          id: string
          marketing_consent: boolean
          name: string | null
          phone: string | null
          updated_at: string
        }
        Insert: {
          address_default?: Json | null
          created_at?: string
          email: string
          id: string
          marketing_consent?: boolean
          name?: string | null
          phone?: string | null
          updated_at?: string
        }
        Update: {
          address_default?: Json | null
          created_at?: string
          email?: string
          id?: string
          marketing_consent?: boolean
          name?: string | null
          phone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      daily_special: {
        Row: {
          badge_label: string | null
          created_at: string
          discount_percent: number | null
          dish_id: string | null
          end_time_local: string | null
          id: number
          is_active: boolean
          label: string | null
          updated_at: string
        }
        Insert: {
          badge_label?: string | null
          created_at?: string
          discount_percent?: number | null
          dish_id?: string | null
          end_time_local?: string | null
          id?: number
          is_active?: boolean
          label?: string | null
          updated_at?: string
        }
        Update: {
          badge_label?: string | null
          created_at?: string
          discount_percent?: number | null
          dish_id?: string | null
          end_time_local?: string | null
          id?: number
          is_active?: boolean
          label?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_special_dish_id_fkey"
            columns: ["dish_id"]
            isOneToOne: false
            referencedRelation: "dishes"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_settings: {
        Row: {
          baseline_min_minutes: number
          baseline_pickup_min: number
          buffer_minutes: number
          closed_weekdays: number[]
          created_at: string
          free_delivery_max_km: number
          id: number
          max_distance_km: number
          max_orders_per_slot: number
          min_cart_cents_above_free: number
          prep_minutes: number
          service_dinner_last_delivery_time: string
          service_dinner_last_order_time: string
          service_dinner_start_time: string
          service_dinner_weekend_last_delivery_time: string
          service_dinner_weekend_last_order_time: string
          service_lunch_last_delivery_time: string
          service_lunch_last_order_time: string
          service_lunch_start_time: string
          slot_duration_minutes: number
          travel_buckets: Json
          updated_at: string
        }
        Insert: {
          baseline_min_minutes?: number
          baseline_pickup_min?: number
          buffer_minutes?: number
          closed_weekdays?: number[]
          created_at?: string
          free_delivery_max_km?: number
          id?: number
          max_distance_km?: number
          max_orders_per_slot?: number
          min_cart_cents_above_free?: number
          prep_minutes?: number
          service_dinner_last_delivery_time?: string
          service_dinner_last_order_time?: string
          service_dinner_start_time?: string
          service_dinner_weekend_last_delivery_time?: string
          service_dinner_weekend_last_order_time?: string
          service_lunch_last_delivery_time?: string
          service_lunch_last_order_time?: string
          service_lunch_start_time?: string
          slot_duration_minutes?: number
          travel_buckets?: Json
          updated_at?: string
        }
        Update: {
          baseline_min_minutes?: number
          baseline_pickup_min?: number
          buffer_minutes?: number
          closed_weekdays?: number[]
          created_at?: string
          free_delivery_max_km?: number
          id?: number
          max_distance_km?: number
          max_orders_per_slot?: number
          min_cart_cents_above_free?: number
          prep_minutes?: number
          service_dinner_last_delivery_time?: string
          service_dinner_last_order_time?: string
          service_dinner_start_time?: string
          service_dinner_weekend_last_delivery_time?: string
          service_dinner_weekend_last_order_time?: string
          service_lunch_last_delivery_time?: string
          service_lunch_last_order_time?: string
          service_lunch_start_time?: string
          slot_duration_minutes?: number
          travel_buckets?: Json
          updated_at?: string
        }
        Relationships: []
      }
      dishes: {
        Row: {
          allergens: string[]
          bg_from: string | null
          bg_to: string | null
          category_id: string
          created_at: string
          description: string
          id: string
          image: string
          image_alt: string
          ingredients: string[]
          is_active: boolean
          is_featured: boolean
          is_most_ordered: boolean
          is_new: boolean
          is_vegan: boolean
          name: string
          pieces: number | null
          price: number
          sort_order: number
          spicy_level: number
          updated_at: string
        }
        Insert: {
          allergens?: string[]
          bg_from?: string | null
          bg_to?: string | null
          category_id: string
          created_at?: string
          description?: string
          id: string
          image?: string
          image_alt?: string
          ingredients?: string[]
          is_active?: boolean
          is_featured?: boolean
          is_most_ordered?: boolean
          is_new?: boolean
          is_vegan?: boolean
          name: string
          pieces?: number | null
          price: number
          sort_order?: number
          spicy_level?: number
          updated_at?: string
        }
        Update: {
          allergens?: string[]
          bg_from?: string | null
          bg_to?: string | null
          category_id?: string
          created_at?: string
          description?: string
          id?: string
          image?: string
          image_alt?: string
          ingredients?: string[]
          is_active?: boolean
          is_featured?: boolean
          is_most_ordered?: boolean
          is_new?: boolean
          is_vegan?: boolean
          name?: string
          pieces?: number | null
          price?: number
          sort_order?: number
          spicy_level?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "dishes_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      marketing_emails_log: {
        Row: {
          customer_id: string | null
          email: string
          email_type: string
          id: string
          resend_id: string | null
          sent_at: string
          subject: string
        }
        Insert: {
          customer_id?: string | null
          email: string
          email_type: string
          id?: string
          resend_id?: string | null
          sent_at?: string
          subject: string
        }
        Update: {
          customer_id?: string | null
          email?: string
          email_type?: string
          id?: string
          resend_id?: string | null
          sent_at?: string
          subject?: string
        }
        Relationships: [
          {
            foreignKeyName: "marketing_emails_log_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      order_status_history: {
        Row: {
          changed_at: string
          changed_by: string | null
          id: string
          notes: string | null
          order_id: string
          status: Database["public"]["Enums"]["order_status"]
        }
        Insert: {
          changed_at?: string
          changed_by?: string | null
          id?: string
          notes?: string | null
          order_id: string
          status: Database["public"]["Enums"]["order_status"]
        }
        Update: {
          changed_at?: string
          changed_by?: string | null
          id?: string
          notes?: string | null
          order_id?: string
          status?: Database["public"]["Enums"]["order_status"]
        }
        Relationships: [
          {
            foreignKeyName: "order_status_history_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          address_line: string | null
          address_notes: string | null
          cancellation_reason: string | null
          cancelled_after_print: boolean
          created_at: string
          customer_email: string
          customer_id: string | null
          customer_name: string
          customer_phone: string
          deliver_by: string
          discount_cents: number
          discount_code: string | null
          driver_notes: string | null
          eta_minutes: number
          fiscal_receipt_issued: boolean
          geo: Json | null
          id: string
          is_test: boolean
          items: Json
          order_number: string
          order_type: Database["public"]["Enums"]["order_type"]
          payment_method: Database["public"]["Enums"]["payment_method"]
          road_distance_m: number | null
          slot_end: string
          slot_start: string
          status: Database["public"]["Enums"]["order_status"]
          status_updated_at: string
          stripe_payment_intent_id: string | null
          stripe_session_id: string | null
          subtotal_cents: number
          tip_cents: number
          total_cents: number
        }
        Insert: {
          address_line?: string | null
          address_notes?: string | null
          cancellation_reason?: string | null
          cancelled_after_print?: boolean
          created_at?: string
          customer_email: string
          customer_id?: string | null
          customer_name: string
          customer_phone: string
          deliver_by: string
          discount_cents?: number
          discount_code?: string | null
          driver_notes?: string | null
          eta_minutes: number
          fiscal_receipt_issued?: boolean
          geo?: Json | null
          id?: string
          is_test?: boolean
          items: Json
          order_number: string
          order_type: Database["public"]["Enums"]["order_type"]
          payment_method: Database["public"]["Enums"]["payment_method"]
          road_distance_m?: number | null
          slot_end: string
          slot_start: string
          status?: Database["public"]["Enums"]["order_status"]
          status_updated_at?: string
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          subtotal_cents: number
          tip_cents?: number
          total_cents: number
        }
        Update: {
          address_line?: string | null
          address_notes?: string | null
          cancellation_reason?: string | null
          cancelled_after_print?: boolean
          created_at?: string
          customer_email?: string
          customer_id?: string | null
          customer_name?: string
          customer_phone?: string
          deliver_by?: string
          discount_cents?: number
          discount_code?: string | null
          driver_notes?: string | null
          eta_minutes?: number
          fiscal_receipt_issued?: boolean
          geo?: Json | null
          id?: string
          is_test?: boolean
          items?: Json
          order_number?: string
          order_type?: Database["public"]["Enums"]["order_type"]
          payment_method?: Database["public"]["Enums"]["payment_method"]
          road_distance_m?: number | null
          slot_end?: string
          slot_start?: string
          status?: Database["public"]["Enums"]["order_status"]
          status_updated_at?: string
          stripe_payment_intent_id?: string | null
          stripe_session_id?: string | null
          subtotal_cents?: number
          tip_cents?: number
          total_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      print_jobs: {
        Row: {
          attempts: number
          claimed_at: string | null
          created_at: string
          id: string
          job_token: string | null
          last_error: string | null
          order_id: string | null
          payload: string
          printed_at: string | null
          printer_mac: string | null
          status: Database["public"]["Enums"]["print_job_status"]
        }
        Insert: {
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          id?: string
          job_token?: string | null
          last_error?: string | null
          order_id?: string | null
          payload: string
          printed_at?: string | null
          printer_mac?: string | null
          status?: Database["public"]["Enums"]["print_job_status"]
        }
        Update: {
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          id?: string
          job_token?: string | null
          last_error?: string | null
          order_id?: string | null
          payload?: string
          printed_at?: string | null
          printer_mac?: string | null
          status?: Database["public"]["Enums"]["print_job_status"]
        }
        Relationships: [
          {
            foreignKeyName: "print_jobs_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      printer_health: {
        Row: {
          id: number
          last_poll_at: string | null
          oldest_pending_age_seconds: number | null
          paper_status: string | null
          pending_jobs_count: number
          printer_mac: string | null
          printing_in_progress: boolean
          updated_at: string
        }
        Insert: {
          id?: number
          last_poll_at?: string | null
          oldest_pending_age_seconds?: number | null
          paper_status?: string | null
          pending_jobs_count?: number
          printer_mac?: string | null
          printing_in_progress?: boolean
          updated_at?: string
        }
        Update: {
          id?: number
          last_poll_at?: string | null
          oldest_pending_age_seconds?: number | null
          paper_status?: string | null
          pending_jobs_count?: number
          printer_mac?: string | null
          printing_in_progress?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      restaurant_settings: {
        Row: {
          city: string | null
          country: string | null
          created_at: string
          cuisine: string[] | null
          delivery_radius_km: number | null
          email: string | null
          facebook: string | null
          full_address: string | null
          hours_closed: string | null
          hours_weekdays: string | null
          hours_weekend: string | null
          id: number
          instagram: string | null
          lat: number | null
          lng: number | null
          manual_pause: boolean
          map_embed_url: string | null
          name: string
          phone: string | null
          phone_display: string | null
          postal_code: string | null
          price_range: string | null
          street: string | null
          tagline: string | null
          updated_at: string
          whatsapp: string | null
          whatsapp_display: string | null
        }
        Insert: {
          city?: string | null
          country?: string | null
          created_at?: string
          cuisine?: string[] | null
          delivery_radius_km?: number | null
          email?: string | null
          facebook?: string | null
          full_address?: string | null
          hours_closed?: string | null
          hours_weekdays?: string | null
          hours_weekend?: string | null
          id?: number
          instagram?: string | null
          lat?: number | null
          lng?: number | null
          manual_pause?: boolean
          map_embed_url?: string | null
          name?: string
          phone?: string | null
          phone_display?: string | null
          postal_code?: string | null
          price_range?: string | null
          street?: string | null
          tagline?: string | null
          updated_at?: string
          whatsapp?: string | null
          whatsapp_display?: string | null
        }
        Update: {
          city?: string | null
          country?: string | null
          created_at?: string
          cuisine?: string[] | null
          delivery_radius_km?: number | null
          email?: string | null
          facebook?: string | null
          full_address?: string | null
          hours_closed?: string | null
          hours_weekdays?: string | null
          hours_weekend?: string | null
          id?: number
          instagram?: string | null
          lat?: number | null
          lng?: number | null
          manual_pause?: boolean
          map_embed_url?: string | null
          name?: string
          phone?: string | null
          phone_display?: string | null
          postal_code?: string | null
          price_range?: string | null
          street?: string | null
          tagline?: string | null
          updated_at?: string
          whatsapp?: string | null
          whatsapp_display?: string | null
        }
        Relationships: []
      }
      stripe_webhook_events_processed: {
        Row: {
          event_id: string
          event_type: string
          processed_at: string
        }
        Insert: {
          event_id: string
          event_type: string
          processed_at?: string
        }
        Update: {
          event_id?: string
          event_type?: string
          processed_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      count_dormant_customers: { Args: { days?: number }; Returns: number }
      is_admin: { Args: { uid: string }; Returns: boolean }
      list_dormant_customers: {
        Args: { days?: number }
        Returns: {
          email: string
          id: string
          last_order_at: string
          marketing_consent: boolean
          name: string
          phone: string
          total_orders: number
        }[]
      }
    }
    Enums: {
      order_status:
        | "received"
        | "confirmed"
        | "preparing"
        | "ready"
        | "in_delivery"
        | "delivered"
        | "cancelled"
        | "refunded"
      order_type: "delivery" | "pickup"
      payment_method: "cash" | "card"
      print_job_status: "pending" | "in_progress" | "printed" | "failed"
    }
    CompositeTypes: { [_ in never]: never }
  }
}
